# for travis-ci
# see also. https://travis-ci.org
git:
  submodules: false

sudo: required

language: php

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - $HOME/.composer/cache
    - bin/.phpunit

php:
  - 7.1
  - 7.2

## see https://github.com/symfony/symfony/blob/e0bdc0c35e9afdb3bee8af172f90e9648c4012fc/.travis.yml#L92-L97
before_install: &php_setup |
  phpenv config-rm xdebug.ini || true
  echo "opcache.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  echo "date.timezone=Asia/Tokyo" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - &composer_install composer install --dev --no-interaction -o --apcu-autoloader

eccube_setup: &eccube_setup |
  echo "APP_ENV=codeception" > .env
  bin/console doctrine:database:create
  bin/console doctrine:schema:create
  bin/console eccube:fixtures:load

jobs:
  fast_finish: true
  allow_failures:
    - env: DATABASE_URL=sqlite:///%kernel.project_dir%/var/eccube.db DATABASE_SERVER_VERSION=3 COVERAGE=1
  include:
    - &unit_test
      stage: Unit Test
      before_install:
        - *php_setup
        - gem install mailcatcher
      install:
        - *composer_install
        - *eccube_setup
        - |
          composer config repositories.eccube '{
              "type": "composer",
              "url": "https://dev-package-api.ec-cube.net",
              "options": {
                  "http": {
                      "header": ["X-ECCUBE-KEY: key_1_1"]
                  }
              }
          }'
        - bin/console eccube:composer:require ec-cube/ProductReview
      env: DATABASE_URL=mysql://root:@localhost/cube4_dev DATABASE_SERVER_VERSION=5
      script:
        - ./bin/phpunit --exclude-group cache-clear
        - ./bin/phpunit --group cache-clear
    - <<: *unit_test
      env: DATABASE_URL=postgres://postgres:password@localhost/cube4_dev DATABASE_SERVER_VERSION=9
    # - stage: Code Coverage
    #   if: type != pull_request
    #   env: DATABASE_URL=sqlite:///%kernel.project_dir%/var/eccube.db DATABASE_SERVER_VERSION=3 COVERAGE=1
    #   before_install:
    #     - *php_setup
    #     - gem install mailcatcher
    #   install:
    #     - *composer_install
    #     - *eccube_setup
    #   script:
    #     - docker run -e DATABASE_URL=sqlite:////usr/src/myapp/var/eccube.db -v "$PWD":/usr/src/myapp:cached -w /usr/src/myapp --rm nanasess/phpdbg phpdbg -qrr -dmemory_limit=-1 ./bin/phpunit --exclude-group cache-clear --coverage-clover=coverage.clover
    #   after_success:
    #     - sed -i.bak -e 's|/usr/src/myapp/||g' coverage.clover
    #     - php vendor/bin/php-coveralls -v -x coverage.clover
    #   after_script:
    #     - wget https://scrutinizer-ci.com/ocular.phar
    #     - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
