# for travis-ci
# see also. https://travis-ci.org
git:
  submodules: false

sudo: required

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - bin/.phpunit

php:
  - 7.2

before_install:
  ## see https://github.com/symfony/symfony/blob/e0bdc0c35e9afdb3bee8af172f90e9648c4012fc/.travis.yml#L92-L97
  - phpenv config-rm xdebug.ini || true
  - echo "opcache.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install --dev --no-interaction -o --apcu-autoloader
  - bin/console doctrine:database:create --env=dev
  - bin/console doctrine:schema:create --env=dev
  - bin/console eccube:fixtures:load --env=dev

jobs:
  include:
    - stage: Test
      env:
        - DB=mysql
        - DATABASE_URL=mysql://root:@localhost/cube4_dev
        - DATABASE_SERVER_VERSION=5
      script:
        - ./bin/phpunit --exclude-group cache-clear
        - ./bin/phpunit --group cache-clear
    - env:
        - DB=pgsql
        - DATABASE_URL=postgres://postgres:password@localhost/cube4_dev
        - DATABASE_SERVER_VERSION=9
      script:
        - ./bin/phpunit --exclude-group cache-clear
        - ./bin/phpunit --group cache-clear
    - stage: Codeception
      script: ./codeception.sh admin01
    - script: ./codeception.sh admin02
    - script: ./codeception.sh admin03
    - script: ./codeception.sh front
